[WIP] Implemented Byzantium fork
ethereum/execution-specs pull request #443
Opened 2022-01-30 18:13 UTC by voith

### What was wrong?

closes #424 #425 #429 #430 # 431  #432

### How was it fixed?
This is still WIP. Opening early for others to contribute. 
Currently, 3309 tests are passing and 1434 are failing. I think a lot of these failures are because of the missing implementations.

#### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://images.all-free-download.com/images/graphicwebp/cute_smiley_dog_210280.webp)
Pic credits: [all-free-download.com](https://all-free-download.com/)

2022-01-31 06:25 UTC, gurukamath commented
@voith I made a list of failed tests by folder. See below



stZeroKnowledge | 370
stPreCompiledContracts | 337
stZeroKnowledge2 | 266
stRevertTest | 86
stStaticCall | 67
stPreCompiledContracts2 | 66
stCallCodes | 47
stCallDelegateCodesHomestead | 37
stReturnDataTest | 31
stCreateTest | 30
stChangedEIP150 | 14
stSystemOperationsTest | 12
stCallCreateCallCodeTest | 10
stEIP150Specific | 9
stRefundTest | 8
stSolidityTest | 5
stSpecialTest | 5
stZeroCallsTest | 4
stQuadraticComplexityTest | 4
stEIP150singleCodeGasPrices | 4
stMemExpandingEIP150Calls | 4
stInitCodeTest | 4
stTransactionTest | 3
stEIP158Specific | 3
stMemoryTest | 2
stHomesteadSpecific | 1
stCreate2 | 1
stDelegatecallTestHomestead | 1
stMemoryStressTest | 1
stRandom2 | 1
stArgsZeroOneBalance | 1

Should we just wait for the other EIPs to be implemented so that some of these go away automatically after implementation?

Having said that, I did take a look at the failing stReturnDataTest and most of them seem to be occurring because the newly implemented opcodes don't seem to increment the evm.pc. (see. returndatacopy and returndatasize)

2022-01-31 07:47 UTC, voith commented
> the newly implemented opcodes don't increment the evm.pc.

You're right! Do you want to submit a PR to my branch? I can then push it here.

> Should we just wait for the other EIPs to be implemented so that some of these go away automatically after implementation?

My plan is to figure out all the tests that can be passed using the existing implementations and then skip the remaining tests that need the precompiles to be implemented. We can [mark the failing tests as slow](https://github.com/voith/eth1.0-specs/blob/0d547e5c2536e1a5d750618fa93c1bcc382e68d9/tests/byzantium/test_state_transition.py#L22) so that they get skipped.

2022-01-31 08:48 UTC, gurukamath commented
> You're right! Do you want to submit a PR to my branch? I can then push it here.

Well, this seems to be a relatively minor fix. So you can just include it along with your next commit. I don't want to make it more complex by creating additional PRs.

> My plan is to figure out all the tests that can be passed using the existing implementations and then skip the remaining tests that need the precompiles to be implemented. We can [mark the failing tests as slow](https://github.com/voith/eth1.0-specs/blob/0d547e5c2536e1a5d750618fa93c1bcc382e68d9/tests/byzantium/test_state_transition.py#L22) so that they get skipped.

Ok. In that case, I will start to look at the `stStaticCall` fails. Those seem like they should have been handled by [EIP-214](https://eips.ethereum.org/EIPS/eip-214). I might need some help here though. I'll contact you over discord if I do.

2022-01-31 12:04 UTC, gurukamath commented
@voith The ` and value != U256(0)` condition in the `CALL` opcode might be the cause of most of the remaining test failures. I'm not entirely sure if the `CALL` opcode necessarily requires the value transferred to be 0 as is being enforced here. Could not find this requirement in the EIPs listed under Byzantium.

Without this condition, I see the following distribution of the failed tests (total 1511 failures)
stZeroKnowledge | 634
stZeroKnowledge2 | 453
stPreCompiledContracts | 329
stRevertTest | 36
stReturnDataTest | 31
stStaticCall | 16
stPreCompiledContracts2 | 6
stCreateTest | 2
stTransactionTest | 2
stRandom2 | 1

Even though the number of failed tests is larger than before, I see this to be more aligned with what we expect to see based on the current state of the implementation. i.e. test failures are mostly from non-implemented parts. Let me know what you think.

2022-01-31 12:14 UTC, voith commented
> The and value != U256(0) condition in the CALL opcode might be the cause of most of the remaining test failures.

EIP-214 says the following about opcode that need to check for Write protection. 

> Any attempts to make state-changing operations inside an execution instance with STATIC set to true will instead throw an exception. These operations include CREATE, CREATE2, LOG0, LOG1, LOG2, LOG3, LOG4, SSTORE, and SELFDESTRUCT. They also include CALL with a non-zero value

> They also include CALL with a non-zero value

Call without value is no different from the static call opcode.

2022-01-31 12:51 UTC, voith commented
@gurukamath I think you've identified the location of the error correctly. 

` ensure(not evm.message.is_static and value != U256(0), WriteProtection)`
should be
`not evm.message.is_static or value != U256(0)`

2022-01-31 12:53 UTC, gurukamath commented
Then I think it should be

if evm.message.is_static:
        ensure(value != U256(0), WriteProtection)

2022-01-31 14:20 UTC, voith commented
I've fixed a few tests that `revert` in a `call-family` frame.
The following check:
```
if isinstance(evm.error, Revert):
```
should be 
```
if isinstance(child_evm.error, Revert):
```

2022-01-31 17:45 UTC, voith commented
@gurukamath I've added you as co-author to the commits that you helped me fix the tests for.

2022-02-01 11:34 UTC, petertdavies requested changes

2022-02-01 11:36 UTC, petertdavies commented on src/ethereum/byzantium/eth_types.py
> +    post_state: Bytes
The encoding is the same as `Uint(0)` for `False` and `Uint(1)` for `True`.

2022-02-16 14:43 UTC, petertdavies commented
You need to add the new folders to the `packages =` list in `setup.cfg`.

2022-02-19 14:10 UTC, voith commented on src/ethereum/byzantium/eth_types.py
> +    post_state: Bytes
We can do this in a separate PR. I think you're the best person to do this.

2022-02-25 18:36 UTC, merged