Rename `src/*/vm/error.py` to `src/*/vm/exceptions.py`
ethereum/execution-specs pull request #514
Opened 2022-05-14 21:12 UTC by BoboTiG

### What was wrong?

Related to Issue #479.

### How was it fixed?

Search & replace.

#### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://pixnio.com/free-images/2017/11/10/2017-11-10-21-10-10.jpg)

2022-05-14 21:13 UTC, BoboTiG commented on src/ethereum/byzantium/vm/exceptions.py
> +Exceptions which cause the EVM to halt exceptionally.
Maybe the repetition is not good here: "exceptions ... exceptionally".

2022-05-27 14:34 UTC, SamWilsn requested changes
Looks good so far! Just needs to be updated to include muir glacier and istanbul, and needs to run the formatting tools.

2022-05-27 14:34 UTC, SamWilsn commented on src/ethereum/byzantium/vm/instructions/environment.py
> +    value = evm.message.data[start_index: start_index + 32]
Would you mind running `black` and `isort` as described in [`README.md`](https://github.com/ethereum/execution-specs/blob/master/README.md#development):

```bash
$ pip install -e ".[doc,lint,test]"
$ isort src                         # Organizes imports.
$ black src                         # Formats code.
```

2022-05-28 12:22 UTC, BoboTiG commented
Updated. And I also adapted docstrings, I missed that from the original commit.

2022-05-31 21:41 UTC, merged