Implement Shanghai
ethereum/execution-specs pull request #692
Opened 2023-01-21 11:39 UTC by gurukamath

### What was wrong?
Shanghai Hardfork not implemented

### How was it fixed?
Implemented EIP-4895, EIP-3651, EIP-3860 and EIP-3855

#### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://upload.wikimedia.org/wikipedia/commons/5/51/Mandarin.duck.arp.jpg)

2023-01-21 11:40 UTC, gurukamath commented
Currently in draft because the tests for some EIPs are in `Merge+EIP` phase rather than `Shanghai`

2023-01-25 13:02 UTC, petertdavies requested changes
I found a couple of nits.

2023-01-25 13:02 UTC, petertdavies commented on src/ethereum/shanghai/spec.py
> +    valid_transaction = True
```python
if ...:
    return False
elif ...:
    return False

return True
```
would be clearer and more idiomatic.

2023-01-25 13:21 UTC, gurukamath commented on src/ethereum/shanghai/spec.py
> +    valid_transaction = True
Updated

2023-01-25 13:31 UTC, gurukamath commented on src/ethereum/shanghai/state.py
> +    modify_state(state, wd.address, increase_recipient_balance)
The `create_ether` function was previously used for issuing mining rewards and is no longer relevant post merge. Having something more closely related to the context of withdrawals makes more sense to me in this case. I am removing the `create_ether` function from Shanghai.

Will also create a new issue to remove the function from Paris

2023-01-25 13:43 UTC, petertdavies approved these changes

2023-01-25 16:04 UTC, merged