Download test fixtures on demand
ethereum/execution-specs pull request #708
Opened 2023-02-01 10:27 UTC by gurukamath

(closes #699 )

### What was wrong?

Currently we use 2 git submodules to get the tests. This is causes issues for people who [depend on us](https://github.com/ethereum/execution-spec-tests/issues/22)

Related to Issue #699 

### How was it fixed?
This change fetches the test fixtures from the relevant repositories/releases
as and when required. As `pytest` is run, it checks at the beginning of the session
if the test fixtures are already available. If not, it fetches them. The following forms
of fetching are supported

1. Download the fixtures from a certain relase artifact (.tar.gz)
2. Clone the fixtures given a repository link and commit hash. Submodules will also be recursively
cloned in this case.

The fetching process is made safe for parallel process runs (with `xdist` for example) by
using a signal file which essentially tells the other processes that a process is already
fetching the relevant fixtures and they just have to wait.

The test run phase starts only once all the fixtures have been downloaded/cloned. In order to change
the links/commit_hash of the fixtures, update `tests/conftest.py`

#### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://upload.wikimedia.org/wikipedia/commons/0/03/Pug_sitting_on_the_ground.png)

2023-02-01 13:03 UTC, petertdavies requested changes
I've identified a bunch of issues with the locking. Although I've suggested fixes above, I think it would be better to outsource to a proper locking library like [filelock](https://pypi.org/project/filelock/), as suggested in the [pytest-xdist documentation](https://pytest-xdist.readthedocs.io/en/latest/how-to.html#making-session-scoped-fixtures-execute-only-once).

2023-02-01 14:54 UTC, gurukamath commented
Thanks for this review. I'll take a look into it.

2023-02-02 21:09 UTC, gurukamath commented on tests/conftest.py
> +    if not os.path.exists(signal_file):
Done. I have used `filelock` for locking

2023-02-02 21:09 UTC, gurukamath commented on tests/conftest.py
> +    signal_file = f"{location}.txt"
Updated

2023-02-02 21:11 UTC, gurukamath commented on tests/conftest.py
> +        os.remove(signal_file)
Done. Since we are actively deleting the lock file in the event of an exception, we won't be expecting stale lock file in a normal scenario.

2023-02-02 21:11 UTC, gurukamath commented
@petertdavies Updated with `filelock`

2023-02-08 16:05 UTC, petertdavies approved these changes

2023-02-08 16:06 UTC, merged