Update pending-opcodes.md (DATA*)
ethereum/execution-specs pull request #868
Opened 2024-01-24 09:34 UTC by pdobacz

### What was wrong?

Related to Issue https://github.com/ipsilon/eof/issues/43

Two opcodes proposed for EOF are in conflict (EXCHANGE and DATALOAD)

### How was it fixed?

Move all DATA* opcodes to the currently empty D section (https://github.com/ipsilon/eof/pull/46)

2024-01-25 20:12 UTC, gumb0 commented
Please update also `proposed-opcodes.md`

2024-01-25 20:13 UTC, gumb0 commented
Also add EXCHANGE and RETURNDATALOAD.

2024-01-29 08:44 UTC, pdobacz commented
@gumb0 

> Please update also `proposed-opcodes.md`

> Also add EXCHANGE and RETURNDATALOAD.

Done & done, please double check

2024-01-29 10:16 UTC, gumb0 requested changes

2024-01-29 10:16 UTC, gumb0 commented on lists/evm/pending-opcodes.md
> +|   0xD3   | DATACOPY        | Bulk EOF data copy                              | TBD - [mega EOF](https://notes.ethereum.org/@ipsilon/mega-eof-specification) |
```suggestion
|   0xD0   | DATALOAD        | Loads data from EOF data section, via stack     | [EIP-7480](https://eips.ethereum.org/EIPS/eip-7480) |
|   0xD1   | DATALOADN       | Loads data from EOF data section, via immediate | [EIP-7480](https://eips.ethereum.org/EIPS/eip-7480) |
|   0xD2   | DATASIZE        | Size of the EOF data section                    | [EIP-7480](https://eips.ethereum.org/EIPS/eip-7480) |
|   0xD3   | DATACOPY        | Bulk EOF data copy                              | [EIP-7480](https://eips.ethereum.org/EIPS/eip-7480) |
```

2024-01-29 10:16 UTC, gumb0 commented on lists/evm/pending-opcodes.md
> +| *0xD3* | *DATACOPY*       | *EOF*                   | *????*           | *TBD - [mega EOF](https://notes.ethereum.org/@ipsilon/mega-eof-specification)* |
```suggestion
| *0xD0* | *DATALOAD*       | *EOF*                   | *????*           | *[EIP-7480](https://eips.ethereum.org/EIPS/eip-7480)* |
| *0xD1* | *DATALOADN*      | *EOF*                   | *????*           | *[EIP-7480](https://eips.ethereum.org/EIPS/eip-7480)* |
| *0xD2* | *DATASIZE*       | *EOF*                   | *????*           | *[EIP-7480](https://eips.ethereum.org/EIPS/eip-7480)* |
| *0xD3* | *DATACOPY*       | *EOF*                   | *????*           | *[EIP-7480](https://eips.ethereum.org/EIPS/eip-7480)* |
```

2024-01-29 10:16 UTC, gumb0 commented on lists/evm/proposed-opcodes.md
> +| [mega EOF](https://notes.ethereum.org/@ipsilon/mega-eof-specification) | 0xFB   | STATICCALL2        | STATICCALL without gas and output memory                                     |
(reordering to keep the list sorted by EIP)
```suggestion
| [EIP-7069](https://eips.ethereum.org/EIPS/eip-7069) | 0xF7   | RETURNDATALOAD     | Loads data returned from a call to the stack                                 |
| [EIP-7069](https://eips.ethereum.org/EIPS/eip-7069) | 0xF8   | CALL2              | CALL without gas and output memory                                           |
| [EIP-7069](https://eips.ethereum.org/EIPS/eip-7069) | 0xF9   | DELEGATECALL2      | DELEGATECALL without gas and output memory                                   |
| [EIP-7069](https://eips.ethereum.org/EIPS/eip-7069) | 0xFB   | STATICCALL2        | STATICCALL without gas and output memory                                     |
| [EIP-7480](https://eips.ethereum.org/EIPS/eip-7480) | 0xD0   | DATALOAD           | Loads data from EOF data section, via stack                                  |
| [EIP-7480](https://eips.ethereum.org/EIPS/eip-7480) | 0xD1   | DATALOADN          | Loads data from EOF data section, via immediate                              |
| [EIP-7480](https://eips.ethereum.org/EIPS/eip-7480) | 0xD2   | DATASIZE           | Size of the EOF data section                                                 |
| [EIP-7480](https://eips.ethereum.org/EIPS/eip-7480) | 0xD3   | DATACOPY           | Bulk data section copy                                                       |
| [mega EOF](https://notes.ethereum.org/@ipsilon/mega-eof-specification) | 0xEC   | CREATE3            | Create from EOF contained initcode                                           |
| [mega EOF](https://notes.ethereum.org/@ipsilon/mega-eof-specification) | 0xED   | CREATE4            | Create from transaction contained initcode                                   |
```

2024-01-29 17:27 UTC, gumb0 approved these changes

2024-03-08 16:00 UTC, SamWilsn approved these changes

2024-03-08 16:27 UTC, pdobacz commented on lists/evm/pending-opcodes.md
> +|   0xED   | CREATE4         | Create from transaction contained initcode      | [EIP-7620](https://eips.ethereum.org/EIPS/eip-7620)                          |
I didn't want to bloat and delay this one. There's going to be yet another update soon (EXT*CALLs), but I want to wait a few days until dust settles and the new names are stable in the EIPs.

But thanks for spotting :+1:

2024-03-08 16:43 UTC, merged